config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :about, :only => :index
  resources :contact, :only => :index

  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true
  validates :author, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/about/index.html.erb
<h1>About Island Color</h1>

<%= react_component('AboutPage') %>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis itaque temporibus, fugiat enim cupiditate voluptate suscipit delectus consequatur incidunt laudantium placeat qui quod est dignissimos voluptatem id reiciendis aut voluptatum!</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis itaque temporibus, fugiat enim cupiditate voluptate suscipit delectus consequatur incidunt laudantium placeat qui quod est dignissimos voluptatem id reiciendis aut voluptatum!</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis itaque temporibus, fugiat enim cupiditate voluptate suscipit delectus consequatur incidunt laudantium placeat qui quod est dignissimos voluptatem id reiciendis aut voluptatum!</p>

app/views/contact/index.html.erb
<!-- contact page -->
<h1>Contact</h1>
<script>
  var s = Snap(200, 200);
  var bigCircle = s.circle(100, 100, 50).drag();
  bigCircle.attr({
    fill: "#bada55",
    stroke: "#000",
    strokeWidth: 5
  });
  var smallCircleA = s.circle(70, 100, 40);
  var smallCircleB = s.circle(140, 100, 40);
  var discs = s.group(smallCircleA, smallCircleB);
  discs.attr({
    fill: "#fff"
  }).animate({r:50}, 1000);
  bigCircle.attr({
    mask: discs
  });

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Island02</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/snap.svg/0.4.1/snap.svg-min.js"></script>
</head>
<body>
<div class='nav'>
  <%= render 'navbar/navbar' %>
</div>
<%= yield %>

</body>
</html>

app/views/navbar/_navbar.html.erb
<div class="container">
  <h3><div class="row">
    <div class="four columns">
      <%= image_tag 'IC_logo_no_bkg' %>
    </div>
    <div class="two columns">
      <%= link_to "About", about_index_path %>
    </div>
    <div class="two columns">
      <%= link_to "Services", "#" %>
    </div>
    <div class="two columns">
      <%= link_to "Work", posts_path %>
    </div>
    <div class="two columns">
      <%= link_to "Contact", contact_index_path %>
    </div>
  </div></h3>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <%= react_component('PostRender', post)%>
<% end %>